[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.build]
# ഫോൾഡറിനുള്ളിൽ കയറി ബിൽഡ് ചെയ്യാൻ
cmds = ["cd StrangerConnectMvc && dotnet publish -c Release -o ../out"]

[start]
# പുറത്തുള്ള out ഫോൾഡറിലെ ഫയൽ റൺ ചെയ്യാൻ
cmd = "dotnet out/StrangerConnectMvc.dll"
